// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdrscvclrkughnaisati.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkcnNjdmNscmt1Z2huYWlzYXRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MDQwODMsImV4cCI6MjA2NTM4MDA4M30.vYubWeFLEFgx0WgPEH98dop5RK6A5OLMr3mdCBotUVk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);